apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-webserver
  namespace: corrjms
  labels:
    app: node-webserver
spec:
  selector:
    matchLabels:
      app: node-webserver
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-webserver
    spec:
      containers:
        - name: node-webserver
          image: docker.corrections-tech.com/node-webserver
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: node-webserver

---
apiVersion: v1
kind: Service
metadata:
  name: node-webserver
  namespace: corrjms
spec:
  selector:
    app: node-webserver
  type: NodePort
  ports:
    - name: node-webserver
      protocol: TCP
      port: 8080
      targetPort: 8080
